#!/bin/bash 
#set -x

if [ -d "venv" ]; then 
    rm -rf venv 
fi

python -m venv venv
source ./venv/bin/activate

echo "Installing all necessary packages ..."

pip install --upgrade pip
pip install libecl 
pip install webviz-config
pip install webviz-config-equinor
pip install requests
pip install requests-toolbelt
pip install msal_extensions
pip install pygobject
pip install python-dotenv
pip install black
pip install -e .

echo "Re-installation completed"
